apiVersion: v1
kind: Service
metadata:
  name: dex
spec:
  type: NodePort
  ports:
  - name: dex
    port: 5556
    protocol: TCP
    targetPort: 5556
    nodePort: 32000
  selector:
    app: dex
  externalIPs:
  - 192.168.0.246
  - 192.168.0.247
  - 192.168.0.248
