kind: ConfigMap
apiVersion: v1
metadata:
  name: dex
data:
  config.yaml: |
    issuer: https://id.apps.wuvt.vt.edu
    storage:
      type: postgres
      config:
        host: postgres.default.svc.cluster.local
        user: $DB_USERNAME
        password: $DB_PASSWORD
        ssl:
          mode: disable
    web:
      https: 0.0.0.0:5556
      tlsCert: /etc/dex/tls/tls.crt
      tlsKey: /etc/dex/tls/tls.key
    frontend:
      issuer: WUVT
      theme: wuvt
    connectors:
    - type: ldap
      id: ldap
      name: WUVT
      config:
        host: zolitude.wuvt.vt.edu:636
        rootCA: /etc/dex/cfg/ldap_ca.pem
        bindDN: uid=$SERVICE_USERNAME,cn=users,cn=accounts,dc=wuvt,dc=vt,dc=edu
        bindPW: $SERVICE_PASSWORD
        userSearch:
          baseDN: cn=users,cn=accounts,dc=wuvt,dc=vt,dc=edu
          filter: '(objectClass=posixAccount)'
          username: uid
          idAttr: uid
          emailAttr: mail
          nameAttr: gecos
        groupSearch:
          baseDN: cn=groups,cn=accounts,dc=wuvt,dc=vt,dc=edu
          filter: '(objectClass=posixGroup)'
          userAttr: DN
          groupAttr: member
          nameAttr: cn
    - type: github
      id: github
      name: GitHub
      config:
        redirectURI: https://id.apps.wuvt.vt.edu/callback
        clientID: $GITHUB_CLIENT_ID
        clientSecret: $GITHUB_CLIENT_SECRET
    - type: oidc
      id: google
      name: Google Apps
      config:
        redirectURI: https://id.apps.wuvt.vt.edu/callback
        clientID: $GOOGLE_CLIENT_ID
        clientSecret: $GOOGLE_CLIENT_SECRET

    oauth2:
      skipApprovalScreen: true
    enablePasswordDB: false
  ldap_ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDkDCCAnigAwIBAgIBATANBgkqhkiG9w0BAQsFADA2MRQwEgYDVQQKDAtXVVZU
    LlZULkVEVTEeMBwGA1UEAwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTE2MDcy
    MTE1MDI0NVoXDTM2MDcyMTE1MDI0NVowNjEUMBIGA1UECgwLV1VWVC5WVC5FRFUx
    HjAcBgNVBAMMFUNlcnRpZmljYXRlIEF1dGhvcml0eTCCASIwDQYJKoZIhvcNAQEB
    BQADggEPADCCAQoCggEBAKH8HyyYkthNerC/ChankDRqOQxaBFXs9vymy3Jvva+z
    W4x68AwQKDzUJRzPU5IflW4/LRWJuKel3l1Gh+seklXlYYuvKm8G732FGHd+jFJw
    KobfMywkACGePp2cfVUCRS8/NPGf869yrQpr9uyDw6/LCfWRN3/nFNUveMl08tD2
    Ut3HUj1pvRwXu505eTGnuaUXnygr2+wiwyx5IJFYv+l6CH+78yrEXsXutJfX9uda
    IUB6g3UVKMusBa3wwlhgrqoYEHKjWpcOJrLmB/hrJzXm8c5xoGc/GJEloAn4cMeH
    516LKhc5VgWTx0srzIPHr0KHmbDem8NA02Hpl2RZTEMCAwEAAaOBqDCBpTAfBgNV
    HSMEGDAWgBTG1duHG/Q68Fb3dNuoNiht+3ms3zAPBgNVHRMBAf8EBTADAQH/MA4G
    A1UdDwEB/wQEAwIBxjAdBgNVHQ4EFgQUxtXbhxv0OvBW93TbqDYobft5rN8wQgYI
    KwYBBQUHAQEENjA0MDIGCCsGAQUFBzABhiZodHRwOi8vem9saXR1ZGUud3V2dC52
    dC5lZHU6ODAvY2Evb2NzcDANBgkqhkiG9w0BAQsFAAOCAQEAGO+usWJ7W1RyJNtb
    TeO2zAyOWTKpNuy5/nzWXR0l+zkIzjHQr/rzmBGkPQK/oqWuAx5YXO3+udhwB52A
    8Sqmnkeevum6Sceb8agd/CI8qW+ToU8GEb2ioc3uyNmOnV7Zc/mzc+0QA0u6FlH9
    M6gKqtMOsw6mx1MkASxPCB11a36mLpbx4mfnLRHiRrjmwQBdlP1ctRDzK91MpoDQ
    YOeF+mmxLWt60PycsohVibmMNULdJg6KN47TEDZ25ynDDn9PSPc8Wm/BecLSY622
    KdPXdgkWxrEIZBDM+p9KiYpcYBQptUC/1TAuzufQXjJXeDFkfT2CG/NCgZwb6sDh
    Umz2wQ==
    -----END CERTIFICATE-----
