apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - name: elasticsearch
    protocol: TCP
    port: 9200
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:7.8.0
        env:
        - name: cluster.name
          value: wuvt
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: "-Xms4G -Xmx4G"
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
      - name: nginx
        image: wuvt/nginx-elasticsearch:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-auth
          mountPath: /etc/nginx/auth
      volumes:
      - name: elasticsearch-data
        hostPath:
          path: /srv/wuvt-elasticsearch-data
      - name: nginx-auth
        secret:
          secretName: elasticsearch-nginx-auth
      nodeName: columbia
      tolerations:
      - key: node-role.kubernetes.io/dbserver
        operator: Exists
        effect: NoSchedule
