apiVersion: v1
kind: Service
metadata:
  labels:
    app: impala
    instance: prod
  name: impala
spec:
  externalIPs:
  - 192.168.0.246
  - 192.168.0.247
  - 192.168.0.248
  ports:
  - name: tcp-8011-5000-t5xgt
    port: 8011
    protocol: TCP
    targetPort: 5000
  selector:
    app: impala
    instance: prod
