apiVersion: v1
kind: Service
metadata:
  name: jira
  labels:
    app: jira
spec:
  selector:
    app: jira
  ports:
  - name: http
    protocol: TCP
    port: 8001
    targetPort: 8080
  externalIPs:
  - 192.168.0.246
  - 192.168.0.247
  - 192.168.0.248
