apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: jira
  name: jira
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jira
    spec:
      containers:
      - name: jira
        image: quay.io/wuvt/docker-atlassian-jira:latest
        env:
        - name: X_PROXY_PORT
          value: "443"
        - name: X_PROXY_SCHEME
          value: "https"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jira-data
          mountPath: /var/atlassian/jira
        - name: jira-logs
          mountPath: /opt/atlassian/jira/logs
      volumes:
      - name: jira-data
        cephfs:
          monitors:
          - 192.168.0.234:6789
          user: k8s
          path: /jira/data
          secretRef:
            name: ceph-k8s
      - name: jira-logs
        cephfs:
          monitors:
          - 192.168.0.234:6789
          user: k8s
          path: /jira/logs
          secretRef:
            name: ceph-k8s
---
apiVersion: v1
kind: Service
metadata:
  name: jira
  labels:
    app: jira
spec:
  selector:
    app: jira
  ports:
  - name: http
    protocol: TCP
    port: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jira
  labels:
    app: jira
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  tls:
    - hosts:
      - "jira.apps.wuvt.vt.edu"
  rules:
    - host: "jira.apps.wuvt.vt.edu"
      http:
        paths:
          - path: /
            backend:
              serviceName: jira
              servicePort: 8080
