apiVersion: v1
kind: Service
metadata:
  name: linx
  labels:
    app: linx
spec:
  selector:
    app: linx
  ports:
  - name: http
    protocol: TCP
    port: 8003
    targetPort: 8080
  externalIPs:
  - 192.168.0.246
  - 192.168.0.247
  - 192.168.0.248
