apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: linx
  name: linx
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: linx
    spec:
      containers:
      - name: linx
        image: andreimarcu/linx-server:latest
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        args:
        - '-sitename=wuvtLinx'
        - '-siteurl=https://linx.apps.wuvt.vt.edu/'
        - '-allowhotlink'
        - '-maxexpiry=604800'
        - '-force-random-filename'
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: linx-files
          mountPath: /data/files
        - name: linx-meta
          mountPath: /data/meta
      volumes:
      - name: linx-files
        cephfs:
          monitors:
            - 192.168.0.234:6789
          path: /linx/files
          user: k8s
          secretRef:
            name: ceph-k8s
      - name: linx-meta
        cephfs:
          monitors:
            - 192.168.0.234:6789
          path: /linx/meta
          user: k8s
          secretRef:
            name: ceph-k8s
---
apiVersion: v1
kind: Service
metadata:
  name: linx
  labels:
    app: linx
spec:
  selector:
    app: linx
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: linx
  labels:
    app: linx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 25g
spec:
  tls:
    - hosts:
      - "linx.apps.wuvt.vt.edu"
  rules:
    - host: "linx.apps.wuvt.vt.edu"
      http:
        paths:
          - path: /
            backend:
              serviceName: linx
              servicePort: 8080
