apiVersion: v1
kind: Service
metadata:
  name: musicbrainz-redis-cache
  labels:
    app: musicbrainz-redis-cache
spec:
  selector:
    app: musicbrainz-redis-cache
  ports:
  - name: redis
    protocol: TCP
    port: 6379
