apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: musicbrainz-webservice
  labels:
    app: musicbrainz-webservice
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: musicbrainz-webservice
    spec:
      containers:
      - name: wuvt-site
        image: quay.io/wuvt/musicbrainz-webservice:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: musicbrainz-webservice-config
          mountPath: /data/config
          readOnly: true
      volumes:
      - name: musicbrainz-webservice-config
        secret:
          secretName: musicbrainz-webservice.config
