apiVersion: v1
kind: Service
metadata:
  name: musicbrainz-webservice
  labels:
    app: musicbrainz-webservice
spec:
  selector:
    app: musicbrainz-webservice
  ports:
  - name: http
    protocol: TCP
    port: 8002
    targetPort: 5000
  externalIPs:
  - 192.168.0.246
  - 192.168.0.247
  - 192.168.0.248
