apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: opensmtpd-ds
  name: opensmtpd
spec:
  selector:
    matchLabels:
      app: opensmtpd-ds
  template:
    metadata:
      labels:
        app: opensmtpd-ds
    spec:
      hostNetwork: true
      containers:
      - name: opensmtpd
        image: wuvt/opensmtpd:latest
        ports:
        - containerPort: 25
          hostPort: 25
        volumeMounts:
        - name: opensmtpd-config
          subPath: smtpd.conf
          mountPath: /etc/smtpd/smtpd.conf
          readOnly: true
        - name: opensmtpd-config
          subPath: mailname
          mountPath: /etc/smtpd/mailname
          readOnly: true
        - name: opensmtpd-tls
          mountPath: /etc/ssl/smtpd
          readOnly: true
      volumes:
      - name: opensmtpd-config
        secret:
          secretName: opensmtpd
      - name: opensmtpd-tls
        secret:
          secretName: opensmtpd.tls
          items:
          - key: tls.crt
            path: cert.pem
          - key: tls.key
            path: privkey.pem
            mode: 384
