apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: opensmtpd
  name: opensmtpd
spec:
  selector:
    matchLabels:
      app: opensmtpd
  template:
    metadata:
      labels:
        app: opensmtpd
    spec:
      containers:
      - name: opensmtpd
        image: wuvt/opensmtpd:latest
        ports:
        - containerPort: 25
        volumeMounts:
        - name: opensmtpd-config
          subPath: smtpd.conf
          mountPath: /etc/smtpd/smtpd.conf
          readOnly: true
        - name: opensmtpd-config
          subPath: mailname
          mountPath: /etc/smtpd/mailname
          readOnly: true
        - name: opensmtpd-config
          subPath: sources
          mountPath: /etc/smtpd/sources
          readOnly: true
        - name: opensmtpd-tls
          mountPath: /etc/ssl/smtpd
          readOnly: true
        - name: spool-smtpd
          mountPath: /var/spool/smtpd
      volumes:
      - name: opensmtpd-config
        secret:
          secretName: opensmtpd
      - name: opensmtpd-tls
        secret:
          secretName: opensmtpd.tls
          items:
          - key: tls.crt
            path: cert.pem
          - key: tls.key
            path: privkey.pem
            mode: 384
      - name: spool-smtpd
        hostPath:
          path: /var/spool/smtpd
---
apiVersion: v1
kind: Service
metadata:
  name: opensmtpd
  labels:
    app: opensmtpd
spec:
  selector:
    app: opensmtpd
  ports:
  - name: smtp
    protocol: TCP
    port: 25
