apiVersion: v1
kind: Service
metadata:
  name: pload-fm
  labels:
    app: pload
    instance: fm
spec:
  selector:
    app: pload
    instance: fm
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 5000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pload-fm
  labels:
    app: pload
    instance: fm
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: pload
        instance: fm
    spec:
      containers:
      - name: pload
        image: wuvt/pload:latest
        env:
        - name: APP_CONFIG_PATH
          value: /data/config/config.json
        volumeMounts:
        - name: pload-fm-config
          mountPath: /data/config
          readOnly: true
        - name: tzinfo
          mountPath: /etc/localtime
          readOnly: true
      volumes:
      - name: pload-fm-config
        secret:
          secretName: pload-fm.config
      - name: tzinfo
        hostPath:
          path: /usr/share/zoneinfo/America/New_York
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pload-fm
  namespace: sso
  #labels:
  #  app: pload
  #  instance: fm
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/proxy-read-timeout: 75s
spec:
  tls:
    - hosts:
      - "playlists-fm.apps.wuvt.vt.edu"
  rules:
    - host: "playlists-fm.apps.wuvt.vt.edu"
      http:
        paths:
          - path: /
            backend:
              serviceName: sso-proxy
              servicePort: 80
            #backend:
            #  serviceName: pload-fm
            #  servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pload-fm-redis
  labels:
    app: pload-redis
    instance: fm
spec:
  selector:
    app: pload-redis
    instance: fm
  ports:
  - name: redis
    protocol: TCP
    port: 6379
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pload-redis
    instance: fm
  name: pload-fm-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pload-redis
        instance: fm
    spec:
      containers:
      - name: redis
        image: redis:4-alpine
        args:
        - '--requirepass $(REDIS_PASSWORD)'
        - '--rename-command CONFIG ""'
        - '--appendonly yes'
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pload-fm-redis
              key: password
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        hostPath:
          path: /media/local-storage/pload-fm-redis-data
      nodeName: columbia
      tolerations:
      - key: node-role.kubernetes.io/dbserver
        operator: Exists
        effect: NoSchedule
