kind: ConfigMap
apiVersion: v1
metadata:
  name: postgres-backup
data:
  postgres.server: postgres.default.svc.cluster.local
  postgres.databases: "jira wuvt wuvtam"
  sftp.dest: "postgres-backup@alexandria.wuvt.vt.edu:postgres/"
