apiVersion: v1
kind: Service
metadata:
  name: retrofling
  labels:
    app: retrofling
spec:
  selector:
    app: retrofling
  ports:
  - name: http
    protocol: TCP
    port: 8004
    targetPort: 8080
  externalIPs:
  - 192.168.0.246
  - 192.168.0.247
  - 192.168.0.248
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: retrofling
  name: retrofling
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: retrofling
    spec:
      containers:
      - name: retrofling
        image: quay.io/wuvt/retrofling:latest
        ports:
        - containerPort: 8080
