apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: retrofling
  name: retrofling
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: retrofling
    spec:
      containers:
      - name: retrofling
        image: ghcr.io/wuvt/retrofling:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: retrofling
  labels:
    app: retrofling
spec:
  selector:
    app: retrofling
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: retrofling
  labels:
    app: retrofling
spec:
  tls:
    - hosts:
      - "retrofling.apps.wuvt.vt.edu"
  rules:
    - host: "retrofling.apps.wuvt.vt.edu"
      http:
        paths:
          - path: /
            backend:
              serviceName: retrofling
              servicePort: 8080
