apiVersion: v1
kind: Service
metadata:
  name: slack-hooks
  labels:
    app: slack-hooks
spec:
  selector:
    app: slack-hooks
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: slack-hooks
  name: slack-hooks
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: slack-hooks
    spec:
      containers:
      - name: slack-hooks
        image: wuvt/slack-hooks:latest
        ports:
        - containerPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: slack-hooks
  labels:
    app: slack-hooks
spec:
  tls:
    - hosts:
      - "slack-hooks.apps.wuvt.vt.edu"
  rules:
    - host: "slack-hooks.apps.wuvt.vt.edu"
      http:
        paths:
          - path: /
            backend:
              serviceName: slack-hooks
              servicePort: 8080
