apiVersion: v1
kind: Service
metadata:
  name: slack-hooks
  labels:
    app: slack-hooks
spec:
  selector:
    app: slack-hooks
  ports:
  - name: http
    protocol: TCP
    port: 8005
    targetPort: 8080
  externalIPs:
  - 192.168.0.246
  - 192.168.0.247
  - 192.168.0.248
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: slack-hooks
  name: slack-hooks
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: slack-hooks
    spec:
      containers:
      - name: slack-hooks
        image: wuvt/slack-hooks:latest
        ports:
        - containerPort: 8080
