apiVersion: v1
kind: Service
metadata:
  labels:
    app: smuggler
    instance: prod
  name: smuggler
spec:
  externalIPs:
  - 192.168.0.246
  - 192.168.0.247
  - 192.168.0.248
  ports:
  - name: tcp-8012-5000-g9i1p
    port: 8012
    protocol: TCP
    targetPort: 5000
  selector:
    app: smuggler
    instance: prod
