apiVersion: v1
kind: Service
metadata:
  name: trackman-am
  labels:
    app: trackman
    instance: am
spec:
  selector:
    app: trackman
    instance: am
  ports:
  - name: http
    protocol: TCP
    port: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: trackman-am
  labels:
    app: trackman
    instance: am
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: trackman
        instance: am
    spec:
      containers:
      - name: trackman
        image: wuvt/trackman:latest
        env:
        - name: APP_CONFIG_PATH
          value: /data/config/config.json
        - name: TZ
          value: America/New_York
        volumeMounts:
        - name: trackman-am-config
          mountPath: /data/config
          readOnly: true
      - name: nginx
        image: quay.io/wuvt/trackman-nginx:latest
        ports:
        - containerPort: 443
        volumeMounts:
        - name: trackman-am-nginx-config
          mountPath: /etc/nginx/conf.d
          readOnly: true
      volumes:
      - name: trackman-am-config
        secret:
          secretName: trackman-am.config
      - name: trackman-am-nginx-config
        secret:
          secretName: trackman-am.nginx
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: trackman-scheduler-am
  labels:
    app: trackman-scheduler
    instance: am
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: trackman-scheduler
        instance: am
    spec:
      containers:
      - name: trackman
        image: wuvt/trackman:latest
        command: ["flask", "run-scheduler"]
        env:
        - name: APP_CONFIG_PATH
          value: /data/config/config.json
        - name: TZ
          value: America/New_York
        volumeMounts:
        - name: trackman-am-config
          mountPath: /data/config
          readOnly: true
      volumes:
      - name: trackman-am-config
        secret:
          secretName: trackman-am.config
---
apiVersion: v1
kind: Service
metadata:
  name: trackman-am-redis
  labels:
    app: trackman-redis
    instance: am
spec:
  selector:
    app: trackman-redis
    instance: am
  ports:
  - name: redis
    protocol: TCP
    port: 6379
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: trackman-redis
    instance: am
  name: trackman-am-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: trackman-redis
        instance: am
    spec:
      containers:
      - name: redis
        image: redis:4-alpine
        args:
        - '--requirepass $(REDIS_PASSWORD)'
        - '--rename-command CONFIG ""'
        - '--appendonly yes'
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: trackman-am-redis
              key: password
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        hostPath:
          path: /media/local-storage/trackman-am-redis-data
      nodeName: columbia
      tolerations:
      - key: node-role.kubernetes.io/dbserver
        operator: Exists
        effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: trackman-am-redis-cache
  labels:
    app: trackman-redis-cache
    instance: am
spec:
  selector:
    app: trackman-redis-cache
    instance: am
  ports:
  - name: redis
    protocol: TCP
    port: 6379
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: trackman-redis-cache
    instance: am
  name: trackman-am-redis-cache
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: trackman-redis-cache
        instance: am
    spec:
      containers:
      - name: redis
        image: redis:4-alpine
        args:
        - '--requirepass $(REDIS_PASSWORD)'
        - '--rename-command CONFIG ""'
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: trackman-am-redis-cache
              key: password
        ports:
        - containerPort: 6379
      tolerations:
      - key: node-role.kubernetes.io/dbserver
        operator: Exists
        effect: NoSchedule
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: trackman-am
  labels:
    app: trackman
    instance: am
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/proxy-read-timeout: 75s
spec:
  tls:
    - hosts:
      - "trackman-am.apps.wuvt.vt.edu"
  rules:
    - host: "trackman-am.apps.wuvt.vt.edu"
      http:
        paths:
          - path: /
            backend:
              serviceName: trackman-am
              servicePort: 80
