apiVersion: v1
kind: Service
metadata:
  name: trackman-am
  labels:
    app: trackman
    instance: am
spec:
  selector:
    app: trackman
    instance: am
  ports:
  - name: https
    protocol: TCP
    port: 7444
    targetPort: 8443
  externalIPs:
  - 192.168.0.246
  - 192.168.0.247
  - 192.168.0.248
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: trackman-am
  labels:
    app: trackman
    instance: am
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: trackman
        instance: am
    spec:
      containers:
      - name: trackman
        image: quay.io/wuvt/trackman:latest
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        env:
        - name: APP_CONFIG_PATH
          value: /data/config/config.json
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: trackman-am-config
          mountPath: /data/config
          readOnly: true
        - name: trackman-am-ssl
          mountPath: /data/ssl
          readOnly: true
        - name: tzinfo
          mountPath: /etc/localtime
          readOnly: true
      volumes:
      - name: trackman-am-config
        secret:
          secretName: trackman-am.config
      - name: trackman-am-ssl
        secret:
          secretName: trackman-am.tls
          items:
          - key: tls.crt
            path: cert.pem
          - key: tls.key
            path: privkey.pem
            mode: 384
      - name: tzinfo
        hostPath:
          path: /usr/share/zoneinfo/America/New_York
