apiVersion: v1
kind: Service
metadata:
  name: trackman-fm-redis
  labels:
    app: trackman-redis
    instance: fm
spec:
  selector:
    app: trackman-redis
    instance: fm
  ports:
  - name: redis
    protocol: TCP
    port: 6379
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: trackman-redis
    instance: fm
  name: trackman-fm-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: trackman-redis
        instance: fm
    spec:
      containers:
      - name: redis
        image: redis:4-alpine
        args:
        - '--requirepass $(REDIS_PASSWORD)'
        - '--rename-command CONFIG ""'
        - '--appendonly yes'
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: trackman-fm-redis
              key: password
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        hostPath:
          path: /media/local-storage/trackman-fm-redis-data
      nodeName: columbia
      tolerations:
      - key: node-role.kubernetes.io/dbserver
        operator: Exists
        effect: NoSchedule
