apiVersion: v1
kind: Service
metadata:
  name: trackman-fm
  labels:
    app: trackman
    instance: fm
spec:
  selector:
    app: trackman
    instance: fm
  ports:
  - name: https
    protocol: TCP
    port: 7443
    targetPort: 443
  externalIPs:
  - 192.168.0.246
  - 192.168.0.247
  - 192.168.0.248
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: trackman-fm
  labels:
    app: trackman
    instance: fm
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: trackman
        instance: fm
    spec:
      containers:
      - name: trackman
        image: quay.io/wuvt/trackman:latest
        env:
        - name: APP_CONFIG_PATH
          value: /data/config/config.json
        volumeMounts:
        - name: trackman-fm-config
          mountPath: /data/config
          readOnly: true
        - name: tzinfo
          mountPath: /etc/localtime
          readOnly: true
      - name: nginx
        image: quay.io/wuvt/trackman-nginx:latest
        ports:
        - containerPort: 443
        volumeMounts:
        - name: trackman-fm-nginx-config
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: trackman-fm-ssl
          mountPath: /data/ssl
          readOnly: true
      volumes:
      - name: trackman-fm-config
        secret:
          secretName: trackman-fm.config
      - name: trackman-fm-nginx-config
        secret:
          secretName: trackman-fm.nginx
      - name: trackman-fm-ssl
        secret:
          secretName: trackman-fm.tls
          items:
          - key: tls.crt
            path: cert.pem
          - key: tls.key
            path: privkey.pem
            mode: 384
      - name: tzinfo
        hostPath:
          path: /usr/share/zoneinfo/America/New_York
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: trackman-scheduler-fm
  labels:
    app: trackman-scheduler
    instance: fm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: trackman-scheduler
        instance: fm
    spec:
      containers:
      - name: trackman
        image: quay.io/wuvt/trackman:latest
        command: ["flask", "run-scheduler"]
        env:
        - name: APP_CONFIG_PATH
          value: /data/config/config.json
        volumeMounts:
        - name: trackman-fm-config
          mountPath: /data/config
          readOnly: true
        - name: tzinfo
          mountPath: /etc/localtime
          readOnly: true
      volumes:
      - name: trackman-fm-config
        secret:
          secretName: trackman-fm.config
      - name: tzinfo
        hostPath:
          path: /usr/share/zoneinfo/America/New_York
---
apiVersion: v1
kind: Service
metadata:
  name: trackman-fm-redis
  labels:
    app: trackman-redis
    instance: fm
spec:
  selector:
    app: trackman-redis
    instance: fm
  ports:
  - name: redis
    protocol: TCP
    port: 6379
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: trackman-redis
    instance: fm
  name: trackman-fm-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: trackman-redis
        instance: fm
    spec:
      containers:
      - name: redis
        image: redis:4-alpine
        args:
        - '--requirepass $(REDIS_PASSWORD)'
        - '--rename-command CONFIG ""'
        - '--appendonly yes'
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: trackman-fm-redis
              key: password
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        hostPath:
          path: /media/local-storage/trackman-fm-redis-data
      nodeName: columbia
      tolerations:
      - key: node-role.kubernetes.io/dbserver
        operator: Exists
        effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: trackman-fm-redis-cache
  labels:
    app: trackman-redis-cache
    instance: fm
spec:
  selector:
    app: trackman-redis-cache
    instance: fm
  ports:
  - name: redis
    protocol: TCP
    port: 6379
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: trackman-redis-cache
    instance: fm
  name: trackman-fm-redis-cache
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: trackman-redis-cache
        instance: fm
    spec:
      containers:
      - name: redis
        image: redis:4-alpine
        args:
        - '--requirepass $(REDIS_PASSWORD)'
        - '--rename-command CONFIG ""'
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: trackman-fm-redis-cache
              key: password
        ports:
        - containerPort: 6379
      tolerations:
      - key: node-role.kubernetes.io/dbserver
        operator: Exists
        effect: NoSchedule
