apiVersion: v1
kind: Service
metadata:
  name: wuvt-site-redis-am
  labels:
    app: wuvt-site-redis
    instance: am
spec:
  selector:
    app: wuvt-site-redis
    instance: am
  ports:
  - name: redis
    protocol: TCP
    port: 6379
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: wuvt-site-redis
    instance: am
  name: wuvt-site-redis-am
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wuvt-site-redis
        instance: am
    spec:
      containers:
      - name: redis
        image: redis:4-alpine
        args:
        - '--requirepass $(REDIS_PASSWORD)'
        - '--rename-command CONFIG ""'
        - '--appendonly yes'
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wuvt-site-redis-am
              key: password
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        hostPath:
          path: /media/local-storage/wuvt-site-redis-am-data
      nodeName: columbia
      tolerations:
      - key: node-role.kubernetes.io/dbserver
        operator: Exists
        effect: NoSchedule
