kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wuvt-site-prod-media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: wuvt-site
      instance: prod
      mount: media
