apiVersion: v1
kind: Service
metadata:
  name: wuvt-site-prod
  labels:
    app: wuvt-site
    instance: prod
spec:
  selector:
    app: wuvt-site
    instance: prod
  ports:
  - name: https
    protocol: TCP
    port: 8443
    targetPort: 8443
  externalIPs:
  - 192.168.0.246
  - 192.168.0.247
  - 192.168.0.248
