apiVersion: v1
kind: Service
metadata:
  name: wuvt-site-redis-am
  labels:
    app: wuvt-site-redis
    instance: am
spec:
  selector:
    app: wuvt-site-redis
    instance: am
  ports:
  - name: redis
    protocol: TCP
    port: 6379
