apiVersion: v1
kind: Service
metadata:
  name: wuvt-site-am
  labels:
    app: wuvt-site
    instance: am
spec:
  selector:
    app: wuvt-site
    instance: am
  ports:
  - name: https
    protocol: TCP
    port: 8444
    targetPort: 8443
  externalIPs:
  - 192.168.0.246
  - 192.168.0.247
  - 192.168.0.248
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wuvt-site-am
  labels:
    app: wuvt-site
    instance: am
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: wuvt-site
        instance: am
    spec:
      containers:
      - name: wuvt-site
        image: ghcr.io/wuvt/wuvt-site:latest
        env:
        - name: APP_CONFIG_PATH
          value: /data/config/config.json
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: wuvt-site-am-config
          mountPath: /data/config
          readOnly: true
        - name: wuvt-site-am-ssl
          mountPath: /data/ssl
          readOnly: true
        - name: wuvt-site-am-media
          mountPath: /data/media
        - name: tzinfo
          mountPath: /etc/localtime
          readOnly: true
      volumes:
      - name: wuvt-site-am-config
        secret:
          secretName: wuvt-site-am.config
      - name: wuvt-site-am-ssl
        secret:
          secretName: wuvt-site-am.tls
          items:
          - key: tls.crt
            path: cert.pem
          - key: tls.key
            path: privkey.pem
            mode: 384
      - name: wuvt-site-am-media
        cephfs:
          monitors:
            - 192.168.0.234:6789
          path: /wuvt-site-am/media
          user: k8s
          secretRef:
            name: ceph-k8s
      - name: tzinfo
        hostPath:
          path: /usr/share/zoneinfo/America/New_York
