apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleplus-grab
  namespace: archiveteam
spec:
  selector:
    matchLabels:
      app: googleplus-grab
  replicas: 2
  template:
    metadata:
      labels:
        app: googleplus-grab
    spec:
      containers:
      - name: googleplus-grab
        image: mutantmonkey/googleplus-grab:latest
        command:
        - "run-pipeline3"
        args:
        - "pipeline.py"
        - "--concurrent"
        - "2"
        - "--disable-web-server"
        - "wuvt"
