apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: sensu
  name: grafana
spec:
  replicas: 1
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      volumes:
        - name: grafana-config
          configMap:
            name: grafana-config
        - name: grafana-data
          cephfs:
            monitors:
              - 192.168.0.234:6789
            path: /sensu/grafana
            user: k8s
            secretRef:
              name: ceph-k8s
      containers:
        - name: grafana
          image: grafana/grafana:5.4.2
          ports:
            - protocol: TCP
              containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: <influxpw>
          volumeMounts:
            - name: grafana-config
              subPath: grafana-provisioning-datasources
              mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
            - name: grafana-config
              subPath: grafana-provisioning-dashboards
              mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
            - name: grafana-data
              mountPath: /var/lib/grafana
        - name: sensu-agent
          image: sensu/sensu:5.1.0
          command: ["/opt/sensu/bin/sensu-agent", "start", "--log-level", "info"]
          env:
            - name: SENSU_BACKEND_URL
              value: ws://sensu-backend.sensu.svc.cluster.local:18081
            - name: SENSU_NAMESPACE
              value: kubernetes
            - name: SENSU_SUBSCRIPTIONS
              value: grafana
            - name: SENSU_DEREGISTER
              value: "true"
            - name: SENSU_STATSD_EVENT_HANDLERS
              value: statsd
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: sensu
spec:
  selector:
    app: grafana
  ports:
    - name: webui
      protocol: TCP
      port: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: sensu
  labels:
    app: grafana
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 4g
spec:
  tls:
    - hosts:
      - "grafana.apps.wuvt.vt.edu"
  rules:
    - host: "grafana.apps.wuvt.vt.edu"
      http:
        paths:
          - path: /
            backend:
              serviceName: grafana
              servicePort: 3000
