apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: sensu
spec:
  selector:
    app: influxdb
  ports:
    - name: flux
      protocol: TCP
      port: 8082
      targetPort: 8082
    - name: api
      protocol: TCP
      port: 8086
      targetPort: 8086
    - name: udp
      protocol: UDP
      port: 8089
      targetPort: 8089
    - name: fluxd
      protocol: TCP
      port: 8093
      targetPort: 8093
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: influxdb
  namespace: sensu
spec:
  replicas: 1
  template:
    metadata:
      name: influxdb
      labels:
        app: influxdb
    spec:
      volumes:
        - name: influxdb-config
          configMap:
            name: influxdb-config
        - name: influxdb-data
          cephfs:
            monitors:
              - 192.168.0.234:6789
            path: /sensu/influxdb
            user: k8s
            secretRef:
              name: ceph-k8s
      containers:
        - name: influxdb
          image: influxdb:1.7.2
          ports:
            - protocol: TCP
              containerPort: 8082
            - protocol: TCP
              containerPort: 8086
            - protocol: UDP
              containerPort: 8089
            - protocol: TCP
              containerPort: 8093
          volumeMounts:
            - name: influxdb-config
              mountPath: /etc/influxdb
            - name: influxdb-data
              mountPath: /var/lib/influxdb
          env:
            - name: INFLUXDB_DB
              value: sensu
            - name: INFLUXDB_USER
              value: sensu
            - name: INFLUXDB_USER_PASSWORD
              value: <influxpw>
        - name: sensu-agent
          image: sensu/sensu:5.1.0
          command: ["/opt/sensu/bin/sensu-agent", "start", "--log-level", "info"]
          env:
            - name: SENSU_BACKEND_URL
              value: ws://sensu-backend.sensu.svc.cluster.local:18081
            - name: SENSU_NAMESPACE
              value: kubernetes
            - name: SENSU_SUBSCRIPTIONS
              value: influxdb
            - name: SENSU_DEREGISTER
              value: "true"
            - name: SENSU_STATSD_EVENT_HANDLERS
              value: statsd
