apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensu-backend
  namespace: sensu
spec:
  replicas: 1
  strategy:
      rollingUpdate:
          maxSurge: 0
  selector:
    matchLabels:
      app: sensu-backend
  template:
    metadata:
      name: sensu-backend
      labels:
        app: sensu-backend
    spec:
      containers:
      - name: sensu-backend
        image: sensu/sensu:5.1.0
        #command: ["/opt/sensu/bin/sensu-backend", "start", "--cert-file", "/etc/sensu/tls/cert.pem", "--key-file", "/etc/sensu/tls/key.pem"]
        command: ["/opt/sensu/bin/sensu-backend", "start", "--log-level", "info"]
        ports:
          - protocol: TCP
            containerPort: 8080
          - protocol: TCP
            containerPort: 8081
          - protocol: TCP
            containerPort: 3000
        volumeMounts:
        - name: sensu-data
          mountPath: /var/lib/sensu
          readOnly: false
          #- name: sensu-tls
          #  mountPath: /etc/sensu/backend.yml
          #  subPath: backend.yml
          #  readOnly: true
      volumes:
          #- name: sensu
          #  secret:
          #    secretName: sensu.tls
          #    items:
          #    - key: tls.crt
          #      path: cert.pem
          #    - key: tls.key
          #      path: key.pem
          #      mode: 384
      - name: sensu-data
        cephfs:
          monitors:
            - 192.168.0.234:6789
          path: /sensu
          user: k8s
          secretRef:
            name: ceph-k8s
---
apiVersion: v1
kind: Service
metadata:
  name: sensu-backend
  namespace: sensu
spec:
  selector:
    app: sensu-backend
  ports:
    - name: api
      protocol: TCP
      port: 8080
    - name: ws
      protocol: TCP
      port: 8081
    - name: dashboard
      protocol: TCP
      port: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sensu-backend
  namespace: sensu
  labels:
    app: sensu-backend
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 4g
spec:
  tls:
    - hosts:
      - "sensu-api.apps.wuvt.vt.edu"
      - "sensu.apps.wuvt.vt.edu"
  rules:
    - host: "sensu-api.apps.wuvt.vt.edu"
      http:
        paths:
          - path: /
            backend:
              serviceName: sensu-backend
              servicePort: 8080
    - host: "sensu.apps.wuvt.vt.edu"
      http:
        paths:
          - path: /
            backend:
              serviceName: sensu-backend
              servicePort: 3000
