apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: sensu
data:
  grafana-provisioning-datasources: |
        apiVersion: 1
        deleteDatasources:
        - name: InfluxDB
          orgId: 1
        datasources:
        - name: InfluxDB
          type: influxdb
          access: proxy
          orgId: 1
          url: http://influxdb.sensu.svc.cluster.local:8086
          database: sensu
          user: sensu
          password: <influxpw>
          version: 1
          editable: true
        - name: InfluxDB Flux
          type: grafana-influxdb-flux-datasource
          access: proxy
          orgId: 1
          url: http://influxdb.sensu.svc.cluster.local:8086
          database: sensu
          user: sensu
          password: <influxpw>
          version: 1
          editable: true
  grafana-provisioning-dashboards: |
        apiVersion: 1
        providers:
        - name: "sensu"
          orgId: 1
          folder: "Sensu"
          type: file
          updateIntervalSeconds: 10
          options:
            path: /var/lib/grafana/dashboards
