apiVersion: v1
kind: ConfigMap
metadata:
  name: upstream-configs
  namespace: sso
data:
  upstream_configs.yml: |-
    - service: eas
      default:
        from: eas.apps.wuvt.vt.edu
        to: http://dasdec.wuvt.vt.edu/
        options:
          preserve_host: true
    - service: files
      default:
        from: files.apps.wuvt.vt.edu
        to: http://alexandria.wuvt.vt.edu/
        options:
          preserve_host: true
          flush_interval: 5s
    - service: kibana
      default:
        from: kibana.apps.wuvt.vt.edu
        to: http://kibana.elk.svc.cluster.local:5601/
        options:
          allowed_groups:
            - it@wuvt.vt.edu
          preserve_host: true
    - service: pload-fm
      default:
        from: playlists-fm.apps.wuvt.vt.edu
        to: http://pload-fm.default.svc.cluster.local:8080/
        options:
          allowed_groups:
            - it@wuvt.vt.edu
            - traffic-staff@wuvt.vt.edu
          preserve_host: true
          skip_auth_regex:
            - ^\/api\/next_track$
            - ^\/api\/underwriting$
          timeout: 30s
    - service: pload-stg
      default:
        from: playlists-stg.apps.wuvt.vt.edu
        to: http://pload-stg.staging.svc.cluster.local:8080/
        options:
          allowed_groups:
            - it@wuvt.vt.edu
            - traffic-staff@wuvt.vt.edu
          preserve_host: true
          skip_auth_regex:
            - ^\/api\/next_track$
            - ^\/api\/underwriting$
          timeout: 60s
    - service: linx
      default:
        from: linx.apps.wuvt.vt.edu
        to: http://linx.default.svc.cluster.local:8080/
        options:
          preserve_host: true
          skip_auth_regex:
            - ^\/[^\/]+$
            - ^\/API\/$
            - ^\/static\/
            - ^\/selif\/
          skip_request_signing: true
          timeout: 30s
          flush_interval: 5s
