apiVersion: v1
kind: ConfigMap
metadata:
  name: upstream-configs
  namespace: sso
data:
  upstream_configs.yml: |-
    - service: files
      default:
        from: files.apps.wuvt.vt.edu
        to: http://alexandria.wuvt.vt.edu/
    - service: eas
      default:
        from: eas.apps.wuvt.vt.edu
        to: http://dasdec.wuvt.vt.edu/
    - service: kibana
      default:
        from: kibana.apps.wuvt.vt.edu
        to: http://kibana.elk.svc.cluster.local:5601/
        options:
          allowed_groups:
            - it@wuvt.vt.edu
