apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - name: elasticsearch
    protocol: TCP
    port: 9200
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
        env:
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
      - name: nginx
        image: quay.io/wuvt/nginx-elasticsearch:1.14
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-auth
          mountPath: /etc/nginx/auth
      volumes:
      - name: elasticsearch-data
        hostPath:
          path: /srv/elasticsearch-data
          #path: /media/local-storage/elasticsearch-data
      - name: nginx-auth
        secret:
          secretName: elasticsearch-nginx-auth
      nodeName: polyus
      tolerations:
      - key: node-role.kubernetes.io/elk
        operator: Exists
        effect: NoSchedule
