apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: kibana
  labels:
    app: kibana
spec:
  selector:
    app: kibana
  ports:
  - name: http
    protocol: TCP
    port: 5601
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: elk
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana-oss:7.4.1
        env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch.elk.svc.cluster.local:9200
        - name: ELASTICSEARCH_USERNAME
          valueFrom:
            secretKeyRef:
              name: elasticsearch
              key: username
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch
              key: password
      - name: nginx
        image: wuvt/nginx-kibana:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-auth
          mountPath: /etc/nginx/auth
      volumes:
      - name: nginx-auth
        secret:
          secretName: kibana-nginx-auth
      tolerations:
      - key: node-role.kubernetes.io/elk
        operator: Exists
        effect: NoSchedule
