apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: elk
  name: logstash-pruner
spec:
  schedule: 0 10 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: logstash-pruner
            image: quay.io/wuvt/logstash-pruner:latest
            env:
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch.elk.svc.cluster.local:9200
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elasticsearch
                  key: username
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch
                  key: password
          restartPolicy: Never
