apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  selector:
    app: logstash
  ports:
  - name: beats
    protocol: TCP
    port: 5043
    targetPort: 5043
  - name: rawtcp
    protocol: TCP
    port: 5044
    targetPort: 5044
  externalIPs:
  - 192.168.0.164
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: quay.io/wuvt/logstash:6.4.2
        env:
        - name: ELASTICSEARCH_HOSTS
          value: http://elasticsearch.elk.svc.cluster.local:9200
        - name: ELASTICSEARCH_USER
          valueFrom:
            secretKeyRef:
              name: elasticsearch
              key: username
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch
              key: password
        volumeMounts:
        - name: logstash-tls
          mountPath: /etc/logstash/tls
        ports:
        - containerPort: 5043
        - containerPort: 5044
      volumes:
      - name: logstash-tls
        secret:
          secretName: logstash.tls
          items:
          - key: tls.crt
            path: cert.pem
          - key: tls.key
            path: privkey.pem
      tolerations:
      - key: node-role.kubernetes.io/elk
        operator: Exists
        effect: NoSchedule
