apiVersion: v1
kind: Service
metadata:
  name: musicbrainz-postgres
  namespace: musicbrainz
  labels:
    app: musicbrainz-postgres
spec:
  selector:
    app: musicbrainz-postgres
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: musicbrainz-postgres
  name: musicbrainz-postgres
  namespace: musicbrainz
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: musicbrainz-postgres
    spec:
      containers:
      - name: postgres
        image: ghcr.io/wuvt/postgres:latest
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: musicbrainz-postgres
              key: password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        hostPath:
          path: /media/local-storage/musicbrainz-postgres-data
      nodeName: columbia
      tolerations:
      - key: node-role.kubernetes.io/dbserver
        operator: Exists
        effect: NoSchedule
