apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: musicbrainz-webservice
  namespace: musicbrainz
  labels:
    app: musicbrainz-webservice
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: musicbrainz-webservice
    spec:
      containers:
      - name: wuvt-site
        image: quay.io/wuvt/musicbrainz-webservice:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: musicbrainz-webservice-config
          mountPath: /data/config
          readOnly: true
      volumes:
      - name: musicbrainz-webservice-config
        secret:
          secretName: musicbrainz-webservice.config
---
apiVersion: v1
kind: Service
metadata:
  name: musicbrainz-webservice
  namespace: musicbrainz
  labels:
    app: musicbrainz-webservice
spec:
  selector:
    app: musicbrainz-webservice
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 5000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: musicbrainz-webservice
  namespace: musicbrainz
  labels:
    app: musicbrainz-webservice
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  tls:
    - hosts:
      - "musicbrainz.apps.wuvt.vt.edu"
  rules:
    - host: "musicbrainz.apps.wuvt.vt.edu"
      http:
        paths:
          - path: /
            backend:
              serviceName: musicbrainz-webservice
              servicePort: 8080
