apiVersion: v1
kind: Service
metadata:
  name: musicbrainz-redis-cache
  namespace: musicbrainz
  labels:
    app: musicbrainz-redis-cache
spec:
  selector:
    app: musicbrainz-redis-cache
  ports:
  - name: redis
    protocol: TCP
    port: 6379
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: musicbrainz-redis-cache
  namespace: musicbrainz
  labels:
    app: musicbrainz-redis-cache
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: musicbrainz-redis-cache
    spec:
      containers:
      - name: redis
        image: redis:4-alpine
        args:
        - '--maxmemory 8MB'
        - '--maxmemory-policy allkeys-lru'
        - '--save ""'
        ports:
        - containerPort: 6379
